- name: Start Nginx
  hosts: web
  become: yes
  vars:
    repo_url: https://github.com/mdn/django-locallibrary-tutorial
    repo_path: /home/{{ ansible_ssh_user }}/django-locallibrary-tutorial
    static_files_root: "{{ repo_path }}/catalog/"
    proxy_pass_target: app_servers

  tasks:
    - name: Clone the Django Local Library repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"

    - name: Setup Nginx
      include_role:
        name: nginx
      vars:
        nginx_template_path: "{{ playbook_dir }}/inventory/templates/nginx.conf.j2"

- name: Deploy Django app using Docker
  hosts: app
  become: yes
  vars:
    docker_image: timurbabs/django
    django_app_container_name: django_locallibrary

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Install Docker
      include_role:
        name: docker

    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run the Django app container
      docker_container:
        name: "{{ django_app_container_name }}"
        image: "{{ docker_image }}"
        state: started
        ports:
           - "127.0.0.1:8000:8000/tcp"

