- name: Start Nginx
  hosts: web
  roles: 
    - iac-ops-is.nginx 
  become: yes
  vars:
    static_files_root: "{{ repo_path }}/catalog/"
    proxy_pass_target: app_servers
    nginx_template_path: "{{ playbook_dir }}/inventory/templates/nginx.conf.j2"

- name: Start Application
  hosts: app
  roles: 
    - iac-ops-is.docker
    - application
  become: yes